- name: Terminate logproducer environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/logproducer/logproducer.yaml
    - vars/aws/logproducer/aws.yaml

  tasks:
    - include: tasks/aws/instances_terminate.yaml
    - include: tasks/aws/keypair_terminate.yaml
    - include: tasks/aws/securitygroup_terminate.yaml

