- name: Provision logproducer environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/logproducer/instances.yaml
    - vars/aws/logproducer/security_groups.yaml

  tasks:
    - include: tasks/aws/keypair.yaml name="logproducer" region="us-west-2"
    - include: tasks/aws/securitygroup.yaml region="us-west-2"
    - include: tasks/aws/instance.yaml keypair="logproducer" region="us-west-2"