- name: Install some dependencies
  apt: name={{ item }} state=installed
  with_items:
    - unzip
    - python-pip

- name: Install python dependencies
  pip: name={{ item }} state=present
  with_items:
    - boto
    - boto3
    - awscli